name: CD - Deploy Frontend to AKS

on:
  workflow_dispatch:
    inputs:
      product_api_ip:
        description: 'External IP of Product Service'
        required: true
      order_api_ip:
        description: 'External IP of Order Service'
        required: true
      aks_cluster_name:
        description: 'Name of the AKS Cluster to deploy to'
        required: true
      aks_resource_group:
        description: 'Resource Group of the AKS Cluster'
        required: true

  workflow_call:
    inputs:
      product_api_ip:
        required: true
        type: string
      order_api_ip:
        required: true
        type: string
      aks_cluster_name:
        required: true
        type: string
      aks_resource_group:
        required: true
        type: string

jobs:
  # Reuse centralized Azure login workflow
  azure_login:
    uses: NachiketJoy/SIT722-week08/.github/workflows/azure-login.yml@main
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}

  deploy_frontend:
    needs: azure_login
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Inject Backend IPs into frontend/main.js
        run: |
          sed -i "s|_PRODUCT_API_URL_|${{ inputs.product_api_ip }}|g" frontend/main.js
          sed -i "s|_ORDER_API_URL_|${{ inputs.order_api_ip }}|g" frontend/main.js
          echo "--- Modified main.js ---"
          cat frontend/main.js
          echo "------------------------"

      - name: Inject dynamic image tag into k8s/frontend.yaml
        run: |
          sed -i "s|image: sit722w8.azurecr.io/frontend:.*|image: sit722w8.azurecr.io/frontend:${{ github.sha }}|g" k8s/frontend.yaml

      - name: Log in to ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Frontend Image
        run: |
          IMAGE_TAG=${{ secrets.ACR_LOGIN_SERVER }}/frontend:${{ github.sha }}
          echo "Building image: $IMAGE_TAG"
          docker build -t $IMAGE_TAG ./frontend/
          echo "Pushing image: $IMAGE_TAG"
          docker push $IMAGE_TAG

      - name: Set Kubernetes context (get AKS credentials)
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ inputs.aks_resource_group }}
          cluster-name: ${{ inputs.aks_cluster_name }}

      - name: Deploy Frontend to AKS
        run: |
          echo "Deploying frontend to AKS cluster: ${{ inputs.aks_cluster_name }}"
          kubectl apply -f k8s/frontend.yaml

      - name: Logout from Azure
        run: az logout || true
